openapi: 3.0.3
info:
  title: Fullstack Lab API
  version: 1.0.0
  description: Backend API for Fullstack Lab
paths:
  /api/auth/csrf/:
    get:
      operationId: auth_csrf_retrieve
      tags:
      - auth
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/auth/login/:
    post:
      operationId: auth_login_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
          description: ''
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      tags:
      - auth
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
          description: ''
  /api/auth/refresh/:
    post:
      operationId: auth_refresh_create
      tags:
      - auth
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
          description: ''
  /api/auth/register/:
    post:
      operationId: auth_register_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
  /api/auth/resend-verification/:
    post:
      operationId: auth_resend_verification_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendVerificationRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ResendVerificationRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ResendVerificationRequest'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResendVerification'
          description: ''
  /api/auth/verify-email/:
    post:
      operationId: auth_verify_email_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyEmailRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VerifyEmailRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VerifyEmailRequest'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyEmail'
          description: ''
  /api/blog/posts/:
    get:
      operationId: blog_posts_list
      tags:
      - blog
      security:
      - cookieJWT: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
          description: ''
    post:
      operationId: blog_posts_create
      tags:
      - blog
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PostCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PostCreateRequest'
        required: true
      security:
      - cookieJWT: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostCreate'
          description: ''
  /api/blog/posts/{id}/:
    get:
      operationId: blog_posts_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this post.
        required: true
      tags:
      - blog
      security:
      - cookieJWT: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
    put:
      operationId: blog_posts_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this post.
        required: true
      tags:
      - blog
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PostRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PostRequest'
        required: true
      security:
      - cookieJWT: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
    patch:
      operationId: blog_posts_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this post.
        required: true
      tags:
      - blog
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPostRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPostRequest'
      security:
      - cookieJWT: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
    delete:
      operationId: blog_posts_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this post.
        required: true
      tags:
      - blog
      security:
      - cookieJWT: []
      responses:
        '204':
          description: No response body
  /api/me/:
    get:
      operationId: me_retrieve
      tags:
      - me
      security:
      - cookieJWT: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: me_partial_update
      tags:
      - me
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUpdateProfileRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUpdateProfileRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUpdateProfileRequest'
      security:
      - cookieJWT: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/me/change-password/:
    post:
      operationId: me_change_password_create
      tags:
      - me
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
        required: true
      security:
      - cookieJWT: []
      responses:
        '200':
          description: No response body
components:
  schemas:
    ChangePasswordRequest:
      type: object
      properties:
        current_password:
          type: string
          writeOnly: true
          minLength: 1
        new_password:
          type: string
          writeOnly: true
          minLength: 1
        new_password_confirm:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - current_password
      - new_password
      - new_password_confirm
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
      required:
      - email
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - email
      - password
    PatchedPostRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        slug:
          oneOf:
          - type: string
            maxLength: 220
            pattern: ^[-a-zA-Z0-9_]+$
          - type: string
            maxLength: 0
        content:
          type: string
          minLength: 1
        status:
          $ref: '#/components/schemas/StatusEnum'
        published_at:
          type: string
          format: date-time
          nullable: true
    PatchedUpdateProfileRequest:
      type: object
      properties:
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
    Post:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        slug:
          oneOf:
          - type: string
            maxLength: 220
            pattern: ^[-a-zA-Z0-9_]+$
          - type: string
            maxLength: 0
        content:
          type: string
        status:
          $ref: '#/components/schemas/StatusEnum'
        author:
          type: string
          format: email
          readOnly: true
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          readOnly: true
        images:
          type: array
          items:
            $ref: '#/components/schemas/PostImage'
          readOnly: true
        published_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - author
      - content
      - created_at
      - id
      - images
      - tags
      - title
      - updated_at
    PostCreate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        content:
          type: string
        status:
          $ref: '#/components/schemas/StatusEnum'
        tags:
          type: array
          items:
            type: string
            maxLength: 100
        published_at:
          type: string
          format: date-time
          nullable: true
      required:
      - content
      - id
      - title
    PostCreateRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        content:
          type: string
          minLength: 1
        status:
          $ref: '#/components/schemas/StatusEnum'
        tags:
          type: array
          items:
            type: string
            minLength: 1
            maxLength: 100
        published_at:
          type: string
          format: date-time
          nullable: true
      required:
      - content
      - title
    PostImage:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        image:
          type: string
          format: uri
        alt_text:
          type: string
          maxLength: 200
        order:
          type: integer
          maximum: 2147483647
          minimum: 0
      required:
      - id
      - image
    PostImageRequest:
      type: object
      properties:
        image:
          type: string
          format: binary
        alt_text:
          type: string
          maxLength: 200
        order:
          type: integer
          maximum: 2147483647
          minimum: 0
      required:
      - image
    PostRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        slug:
          oneOf:
          - type: string
            maxLength: 220
            pattern: ^[-a-zA-Z0-9_]+$
          - type: string
            maxLength: 0
        content:
          type: string
          minLength: 1
        status:
          $ref: '#/components/schemas/StatusEnum'
        published_at:
          type: string
          format: date-time
          nullable: true
      required:
      - content
      - title
    Register:
      type: object
      properties:
        email:
          type: string
          format: email
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
      required:
      - email
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        password:
          type: string
          writeOnly: true
          minLength: 1
        password_confirm:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - email
      - password
      - password_confirm
    ResendVerification:
      type: object
      properties:
        email:
          type: string
          format: email
      required:
      - email
    ResendVerificationRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
      required:
      - email
    StatusEnum:
      enum:
      - draft
      - published
      - archived
      type: string
      description: |-
        * `draft` - پیش‌نویس
        * `published` - منتشر شده
        * `archived` - آرشیو شده
    Tag:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        slug:
          oneOf:
          - type: string
            maxLength: 120
            pattern: ^[-a-zA-Z0-9_]+$
          - type: string
            maxLength: 0
      required:
      - id
      - name
    TagRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        slug:
          oneOf:
          - type: string
            maxLength: 120
            pattern: ^[-a-zA-Z0-9_]+$
          - type: string
            maxLength: 0
      required:
      - name
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          readOnly: true
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        email_verified:
          type: boolean
          readOnly: true
        is_active:
          type: boolean
          readOnly: true
          title: Active
          description: Designates whether this user should be treated as active. Unselect
            this instead of deleting accounts.
        is_staff:
          type: boolean
          readOnly: true
          title: Staff status
          description: Designates whether the user can log into this admin site.
        is_superuser:
          type: boolean
          readOnly: true
          title: Superuser status
          description: Designates that this user has all permissions without explicitly
            assigning them.
        date_joined:
          type: string
          format: date-time
          readOnly: true
        last_login:
          type: string
          format: date-time
          readOnly: true
          nullable: true
      required:
      - date_joined
      - email
      - email_verified
      - id
      - is_active
      - is_staff
      - is_superuser
      - last_login
    VerifyEmail:
      type: object
      properties:
        email:
          type: string
          format: email
        code:
          type: string
          maxLength: 6
          minLength: 6
          pattern: ^\d{6}$
      required:
      - code
      - email
    VerifyEmailRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
        code:
          type: string
          minLength: 6
          maxLength: 6
          pattern: ^\d{6}$
      required:
      - code
      - email
  securitySchemes:
    cookieJWT:
      type: apiKey
      in: cookie
      name: access
