/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */
import type { BlogPostsListStatus } from './blogPostsListStatus';

export type BlogPostsListParams = {
author?: number;
created_after?: string;
created_before?: string;
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
published_after?: string;
published_before?: string;
/**
 * A search term.
 */
search?: string;
/**
 * * `draft` - پیش‌نویس
* `published` - منتشر شده
* `archived` - آرشیو شده
 */
status?: BlogPostsListStatus;
};
