/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */

export type BlogPostsListStatus = typeof BlogPostsListStatus[keyof typeof BlogPostsListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlogPostsListStatus = {
  archived: 'archived',
  draft: 'draft',
  published: 'published',
} as const;
