/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordRequest {
  /** @minLength 1 */
  current_password: string;
  /** @minLength 1 */
  new_password: string;
  /** @minLength 1 */
  new_password_confirm: string;
}
