/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */

export interface Comment {
  readonly id: number;
  post: number;
  readonly user: string;
  content: string;
  readonly is_approved: boolean;
  readonly created_at: string;
  readonly updated_at: string;
}
