/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */
import type { Comment } from './comment';

export interface PaginatedCommentList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Comment[];
}
