/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */
import type { PostSlug } from './postSlug';
import type { StatusEnum } from './statusEnum';
import type { Tag } from './tag';
import type { PostImage } from './postImage';

export interface Post {
  readonly id: number;
  /** @maxLength 200 */
  title: string;
  slug?: PostSlug;
  content: string;
  status?: StatusEnum;
  readonly author: string;
  readonly tags: readonly Tag[];
  readonly images: readonly PostImage[];
  /** @nullable */
  published_at?: string | null;
  readonly created_at: string;
  readonly updated_at: string;
}
