/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */
import type { StatusEnum } from './statusEnum';

export interface PostCreate {
  readonly id: number;
  /** @maxLength 200 */
  title: string;
  content: string;
  status?: StatusEnum;
  tags?: string[];
  /** @nullable */
  published_at?: string | null;
}
