/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */

export interface PostImage {
  readonly id: number;
  image: string;
  /** @maxLength 200 */
  alt_text?: string;
  /**
   * @minimum 0
   * @maximum 2147483647
   */
  order?: number;
}
