/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */
import type { StatusEnum } from './statusEnum';

export interface PostRequest {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /** @minLength 1 */
  content: string;
  status?: StatusEnum;
  /** @nullable */
  published_at?: string | null;
}
