/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequest {
  /** @minLength 1 */
  email: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  /** @minLength 1 */
  password: string;
  /** @minLength 1 */
  password_confirm: string;
}
