/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `draft` - پیش‌نویس
* `published` - منتشر شده
* `archived` - آرشیو شده
 */
export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusEnum = {
  draft: 'draft',
  published: 'published',
  archived: 'archived',
} as const;
