/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */
import type { TagSlug } from './tagSlug';

export interface Tag {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  slug?: TagSlug;
}
