/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */
import type { TagRequestSlug } from './tagRequestSlug';

export interface TagRequest {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  slug?: TagRequestSlug;
}
