/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  readonly id: number;
  readonly email: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  readonly email_verified: boolean;
  /** Designates whether this user should be treated as active. Unselect this instead of deleting accounts. */
  readonly is_active: boolean;
  /** Designates whether the user can log into this admin site. */
  readonly is_staff: boolean;
  /** Designates that this user has all permissions without explicitly assigning them. */
  readonly is_superuser: boolean;
  readonly date_joined: string;
  /** @nullable */
  readonly last_login: string | null;
}
