/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fullstack Lab API
 * Backend API for Fullstack Lab
 * OpenAPI spec version: 1.0.0
 */

export interface VerifyEmail {
  email: string;
  /**
   * @minLength 6
   * @maxLength 6
   * @pattern ^\d{6}$
   */
  code: string;
}
